DemoDatatables/DemoDatatables/Controllers/DemoController.cs
using DemoDatatables.Models;
using System;
using System.Linq;
using System.Web.Mvc;
using System.Linq.Dynamic;
using System.Data.Entity;

using System.Collections.Generic;

namespace DemoDatatables.Controllers
{
    public class DemoController : Controller
    {
        // GET: Demo
        public ActionResult ShowGrid()
        {
            return View();
        }

        public ActionResult LoadData()
        {
            try
            {
                //Creating instance of DatabaseContext class
                using (DatabaseContext _context = new DatabaseContext())
                {
                    var draw = Request.Form.GetValues("draw").FirstOrDefault(); //dibuja secuencia de devoluciones de forma asincrona
                    var start = Request.Form.GetValues("start").FirstOrDefault(); //inicio en el conjunto de datos actual(0 basado en índice, es decir, 0 es el primer registro).
                    var length = Request.Form.GetValues("length").FirstOrDefault();// Número de registros que la tabla puede mostrar
                    var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                    var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                    var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();


                    //Paging Size (10,20,50,100)  
                    int pageSize = length != null ? Convert.ToInt32(length) : 0;
                    int skip = start != null ? Convert.ToInt32(start) : 0;
                    int recordsTotal = 0;

                    // obteniendo todos los datos de la orden 
                    var ordenData = (from temporden in _context.smm_OrderMaster
                                     select temporden);

                    //Sorting (clasificación) 
                    if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
                    {
                        ordenData = ordenData.OrderBy(sortColumn + " " + sortColumnDir);
                    }

                    ////Search  buscar
                    if (!string.IsNullOrEmpty(searchValue))
                    {
                        ordenData = ordenData.Where(m => m.OrderID == searchValue
                        || m.CustomerType == searchValue || m.CustomerName == searchValue || m.Email == searchValue || m.ProductType==searchValue );
                    }

                    //total number of rows count   
                    recordsTotal = ordenData.Count();
                    //Paging   
                    var data = ordenData.Skip(skip).Take(pageSize).ToList();

                    return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data },JsonRequestBehavior.AllowGet);
                    
                }
            }

            catch (Exception)
            {
                
                throw;
            }

        }

        [HttpGet]
        public ActionResult Edit(string ID)
        {
            try
            {
                using (DatabaseContext _context = new DatabaseContext())
                {
                    var Orden = (from smm_OrderMaster in _context.smm_OrderMaster
                                 where smm_OrderMaster.OrderID == ID
                                 select smm_OrderMaster).FirstOrDefault();

                    return View(Orden);
                }
            }
            catch (Exception)
            {
                throw;
            }
        }


        [HttpPost]
        public JsonResult DeleteOrden(string ID)
        {
            using (DatabaseContext _context = new DatabaseContext())
            {
                var Orden = _context.smm_OrderMaster.Find(ID);

                if (ID == null)
                    return Json(data: "Not Deleted", behavior: JsonRequestBehavior.AllowGet);
                _context.smm_OrderMaster.Remove(Orden);
                _context.SaveChanges();

                return Json(data: "Deleted", behavior: JsonRequestBehavior.AllowGet);
            }
        }

    }
}

DemoDatatables/DemoDatatables/Views/Demo/Edit.cshtml
@model DemoDatatables.Models.smm_OrderMaster

@{
    Layout = null;
}
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <h4>Smm_Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OrderID)

        <div class="form-group">
            @Html.LabelFor(model => model.OrderDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.OrderDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrderDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.CustomerType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.ProductType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductModel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.ProductModel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductModel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.ProductDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProductDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PartNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.PartNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PartNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SerialNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.SerialNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SerialNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FailureType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.FailureType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FailureType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SeqNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.SeqNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SeqNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.inWarranty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.inWarranty, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.inWarranty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DanoEmpaque, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.DanoEmpaque, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DanoEmpaque, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DanoEquipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.DanoEquipo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DanoEquipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.CID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Validado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Validado, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Validado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IntRR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.IntRR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IntRR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContDiario, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.ContDiario, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContDiario, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-4">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "ShowGrid", "Demo")
    </div>
</body>
</html>

DemoDatatables/DemoDatatables/Views/Demo/ShowGrid.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowGrid</title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />

    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>





    <script>
        $(document).ready(function () {
            $("#demoGrid").DataTable({

                "processing": true, // muestra el mensaje de procesando 
                "serverSide": true, // calculos del procesamiento (filtrado, paginación y clasificación)
                "filter": true, // habilita el cuadro de busqueda (search box)
                "orderMulti": false, // for disable multiple column at once ordena multiples columnas 
                "pageLength": 10,

                "ajax": {
                    "url": "/Demo/LoadData",
                    "type": "POST",
                    "datatype": "json"
                },

                "columnDefs":
                    [{
                        "targets": [0],
                        "visible": true,
                        "searchable": false
                    },
                    {
                        "targets": [17],
                        "searchable": true,
                        "orderable": false
                    },
                    {
                        "targets": [18],
                        "searchable": true,
                        "orderable": false
                    },
                    {
                        "targets": [19],
                        "searchable": true,
                        "orderable": false
                    }
               ],

                "columns": [
                    { "data": "OrderID", "name": "OrderID", "autoWidth": true },
                    { "data": "OrderDate", "name": "OrderDate", "autoWidth": true },
                    { "data": "CustomerType", "title": "CustomerType", "name": "CustomerType", "autoWidth": true },
                    { "data": "CustomerName", "name": "CustomerName", "autoWidth": true },
                    { "data": "Email", "name": "Email", "autoWidth": true },
                    { "data": "ProductType", "name": "ProductType", "autoWidth": true },
                    { "data": "ProductModel", "name": "ProductModel", "autoWidth": true },
                    { "data": "ProductDescription", "name": "ProductDescription", "autoWidth": true },
                    { "data": "PartNumber", "name": "PartNumber", "autoWidth": true },
                    { "data": "SerialNumber", "name": "SerialNumber", "autoWidth": true },
                    { "data": "FailureType", "name": "FailureType", "autoWidth": true },
                    { "data": "Comment", "name": "Comment", "autoWidth": true },
                    { "data": "Status", "name": "Status", "autoWidth": true },
                    { "data": "SeqNo", "name": "SeqNo", "autoWidth": true },
                    { "data": "inWarranty", "name": "inWarranty", "autoWidth": true },
                    { "data": "DanoEmpaque", "name": "DanoEmpaque", "autoWidth": true },
                    { "data": "DanoEquipo", "name": "DanoEquipo", "autoWidth": true },
                    { "data": "CID", "name": "CID", "autoWidth": true },
                    { "data": "Validado", "name": "Validado", "autoWidth": true },
                    { "data": "IntRR", "name": "IntRR", "autoWidth": true },
                    { "data": "ContDiario", "name": "ContDiario", "autoWidth": true }

                    //{ "data": "Bit", "name": "Bit", "autowidth": true },

                    //{
                    //    "render": function (data, type, full, meta) {
                    //        return '<a class="btn btn-info" href="/Demo/Edit/' + full.OrderID + '">Edit</a>';
                    //    }
                    //},

                    //{
                    //    data: null, render: function (data, type, row) {
                    //        return "<a href='#' class='btn btn-danger' onclick=DeleteData('" + row.OrderID + "'); >Delete</a>";
                    //    }
                    //},

                ]

            });
        });
    </script>

    @*<script>

        function DeleteData(OrderID) {
            if (confirm("Are you sure you want to delete ...?")) {
                Delete(OrderID);
            }
            else {
                return false;
            }
        }


        function Delete(OrderID) {
            var url = '@Url.Content("~/")' + "Demo/DeleteOrder";
            $.post(url, { ID: OrderID }, function (data) {
                if (data == "Deleted") {
                    alert("Delete Order !");
                    oTable = $('#demoGrid').DataTable();
                    oTable.draw();
                }
                else {
                    alert("Something Went Wrong!");
                }
            });
        }
    </script>*@

</head>
<body>
    <div class="container-fluid">
        <br />
        @*<div style="width:100%; margin:0 auto;">*@
            <table id="demoGrid" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>OrderID</th>
                        <th>OrderDate</th>
                        <th>CustomerType</th>
                        <th>CustomerName</th>
                        <th>Email</th>
                        <th>ProductType</th>
                        <th>ProductModel</th>
                        <th>ProductDescription</th>
                        <th>PartNumber</th>
                        <th>SerialNumber</th>
                        <th>FailureType</th>
                        <th>Comment</th>
                        <th>Status</th>
                        <th>SeqNo</th>
                        <th>inWarranty</th>
                        <th>DanoEmpaque</th>
                        <th>DanoEquipo</th>
                        <th>CID</th>
                        <th>Validado</th>
                        <th>IntRR</th>
                        <th>ContDiario</th>
                        @*<th>Edit</th>
                        <th>Delete</th>*@
                    </tr>
                </thead>
            </table>
        </div>
    @*</div>*@
</body>
</html>