DemoDatatables/DemoDatatables/Models/OrderStatus.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DemoDatatables.Models
{

    [Table("sc_OrderStatus")]
    public class sc_OrderStatus
    {
        [Key]

        public string OrderID { get; set; }
        public string Status { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Comment { get; set; }
        public System.Guid UID { get; set; }
    }
}

DemoDatatables/DemoDatatables/Controllers/OrderStatusController.cs
using DemoDatatables.Models;
using System;
using System.Linq;
using System.Linq.Dynamic;
using System.Web.Mvc;
using System.Data.Entity;

namespace DemoDatatables.Controllers
{
    public class OrderStatusController : Controller
    {
        // GET: OrderStatus
        public ActionResult showOrderStatus()
        {
            return View();
        }
        public ActionResult LoadOrderStatus()
        {
            try
            {
                //Creating instance of DatabaseContext class
                using (DatabaseContext _context = new DatabaseContext())
                {
                    var draw = Request.Form.GetValues("draw").FirstOrDefault(); //dibuja secuencia de devoluciones de forma asincrona
                    var start = Request.Form.GetValues("start").FirstOrDefault(); //inicio en el conjunto de datos actual(0 basado en índice, es decir, 0 es el primer registro).
                    var length = Request.Form.GetValues("length").FirstOrDefault();// Número de registros que la tabla puede mostrar
                    var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                    var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                    var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();


                    //Paging Size (10,20,50,100)  
                    int pageSize = length != null ? Convert.ToInt32(length) : 0;
                    int skip = start != null ? Convert.ToInt32(start) : 0;
                    int recordsTotal = 0;

                    // obteniendo todos los datos de la orden 
                    var ordenData = (from temporden in _context.sc_OrderStatus
                                     select temporden);

                    //Sorting (clasificación) 
                    if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
                    {
                        ordenData = ordenData.OrderBy(sortColumn + " " + sortColumnDir);
                    }

                    ////Search  buscar
                    if (!string.IsNullOrEmpty(searchValue))
                    {
                        ordenData = ordenData.Where(m => m.OrderID == searchValue
                        || m.Status == searchValue || m.Comment == searchValue || m.CreateBy == searchValue);
                    }

                    //total number of rows count   
                    recordsTotal = ordenData.Count();
                    //Paging   
                    var data = ordenData.Skip(skip).Take(pageSize).ToList();

                    return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data }, JsonRequestBehavior.AllowGet);

                }
            }

            catch (Exception)
            {

                throw;
            }

        }

        [HttpGet]
        public ActionResult Edit(string ID)
        {
            try
            {
                using (DatabaseContext _context = new DatabaseContext())
                {
                    var Orden = (from sc_OrderStatus in _context.sc_OrderStatus
                                 where sc_OrderStatus.OrderID == ID
                                 select sc_OrderStatus).FirstOrDefault();

                    return View(Orden);
                }
            }
            catch (Exception)
            {
                throw;
            }
        }


        [HttpPost]
        public JsonResult DeleteOrden(string ID)
        {
            using (DatabaseContext _context = new DatabaseContext())
            {
                var Orden = _context.sc_OrderStatus.Find(ID);

                if (ID == null)
                    return Json(data: "Not Deleted", behavior: JsonRequestBehavior.AllowGet);
                _context.sc_OrderStatus.Remove(Orden);
                _context.SaveChanges();

                return Json(data: "Deleted", behavior: JsonRequestBehavior.AllowGet);
            }
        }

    }
}
    

DemoDatatables/DemoDatatables/Views/Orderstatus/EditOrderStatus.cshtml
@model DemoDatatables.Models.sc_OrderStatus

@{
    Layout = null;
}
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sc Order Status</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OrderID)

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CreateBy, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.CreateBy, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateBy, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.CreateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.UID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-4">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
    }

    <div>
        @Html.ActionLink("Back to List", "ShowOrderStatus", "OrderStatus")
    </div>
</body>
</html>

DemoDatatables/DemoDatatables/Views/Orderstatus/ShowOrderStatus.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowOrderStatus</title>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />

    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>





    <script>
        $(document).ready(function () {
            $("#demoOrder").DataTable({

                "processing": true, // muestra el mensaje de procesando
                "serverSide": true, // calculos del procesamiento (filtrado, paginación y clasificación)
                "filter": true, // habilita el cuadro de busqueda (search box)
                "orderMulti": false, // for disable multiple column at once ordena multiples columnas
                "pageLength": 50,

                "ajax": {
                    "url": "/OrderStatus/LoadOrderStatus",
                    "type": "POST",
                    "datatype": "json"
                },

                "columnDefs":
                    [{
                        "targets": [0],
                        "visible": true,
                        "searchable": true
                    },
                    {
                        "targets": [1],
                        "visible": true,
                         "searchable": false
                    },
                    {
                        "targets": [2],
                        "searchable": true,
                        "orderable": false
                    },
                    {
                        "targets": [3],
                        "searchable": true,
                        "orderable": false
                    },
                    {
                        "targets": [4],
                        "searchable": true,
                        "orderable": false
                    },
                    {
                         "targets": [5],
                         "searchable": false,
                         "orderable": false
                    }

                    ],

                "columns": [
                    { "data": "OrderID", "name": "OrderID", "autoWidth": true },
                    { "data": "Status", "name": "Status", "autoWidth": true },
                    { "data": "CreateBy", "name": "CreateBy", "autoWidth": true },
                    { "data": "CreateDate", "name": "CreateDate", "autoWidth": true },
                    { "data": "Comment", "name": "Comment", "autoWidth": true },
                    { "data": "UID", "name": "UID", "autoWidth": true }]

            });
        });
    </script>

    @*<script>

        function DeleteData(OrderID) {
            if (confirm("Are you sure you want to delete ...?")) {
                Delete(OrderID);
            }
            else {
                return false;
            }
        }


        function Delete(OrderID) {
            var url = '@Url.Content("~/")' + "OrderStatus/DeleteOrder";
            $.post(url, { ID: OrderID }, function (data) {
                if (data == "Deleted") {
                    alert("Delete Order !");
                    oTable = $('#demoOrder').DataTable();
                    oTable.draw();
                }
                else {
                    alert("Something Went Wrong!");
                }
            });
        }
    </script>*@

</head>
<body>
    <div class="container">
        <br />
        @*<div style="width:100%; margin:0 auto;">*@
        <table id="demoOrder" class="table table-striped table-bordered dt-responsive nowrap" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>OrderID</th>
                    <th>Status</th>
                    <th>CreateBy</th>
                    <th>CreateDate</th>
                    <th>Comment</th>
                    <th>UID</th>
                </tr>
            </thead>
        </table>
    </div>
    @*</div>*@
</body>
</html>